const std = @import("std");
const crypto_mod = @import("src/quic/crypto.zig");

pub fn main() !void {
    var arena = std.heap.ArenaAllocator.init(std.heap.page_allocator);
    defer arena.deinit();
    const alloc = arena.allocator();
    _ = alloc;

    // From the last successful client packet log:
    // Client DCID: {224, 54, 68, 173, 104, 230, 106, 0}
    // Client SCID: Generated by the client
    //Server response DCID: {224, 54, 68, 173, 104, 230, 106, 0} (echoed client DCID)
    // Server response SCID: {118, 88, 181, 116}
    //
    // According to RFC 9001, both use the client's DCID for Initial key derivation.
    // But what if the server is using something else?

    const client_dcid = [_]u8{224, 54, 68, 173, 104, 230, 106, 0};
    const server_scid = [_]u8{118, 88, 181, 116};
    const empty = [_]u8{};

    // Expected decryption key from the logs:
    const expected_key = [_]u8{107, 181, 31, 251, 37, 254, 78, 44, 108, 174, 153, 141, 49, 110, 125, 1};

    std.debug.print("Testing which DCID the server used for Initial key derivation:\n\n", .{});

    std.debug.print("1. Using client's DCID (should be RFC-compliant):\n", .{});
    var keys = try crypto_mod.deriveInitialKeyMaterial(&client_dcid, 0x00000001, false);
    std.debug.print("   Server key: {any}\n", .{keys[0].key});
    std.debug.print("   Match: {}\n\n", .{std.mem.eql(u8, &keys[0].key, &expected_key)});

    std.debug.print("2. Using server's SCID:\n", .{});
    keys = try crypto_mod.deriveInitialKeyMaterial(&server_scid, 0x00000001, false);
    std.debug.print("   Server key: {any}\n", .{keys[0].key});
    std.debug.print("   Match: {}\n\n", .{std.mem.eql(u8, &keys[0].key, &expected_key)});

    std.debug.print("3. Using empty DCID:\n", .{});
    keys = try crypto_mod.deriveInitialKeyMaterial(&empty, 0x00000001, false);
    std.debug.print("   Server key: {any}\n", .{keys[0].key});
    std.debug.print("   Match: {}\n\n", .{std.mem.eql(u8, &keys[0].key, &expected_key)});

    std.debug.print("Expected server key: {any}\n", .{expected_key});
}
