#!/usr/bin/env bash
# Run the MoQ interop test client against a list of relays and write the
# results to SPEC/moq-interop-results.md.
#
#   tools/moq_interop.sh                 # local relays, both drafts
#   DRAFTS=18 tools/moq_interop.sh       # one draft
#   PUBLIC=1 tools/moq_interop.sh        # also the public ones
#   tools/moq_interop.sh <url> [<url>…]  # specific relays
#
# Relays are named by URL scheme: https:// is WebTransport, moqt:// is
# native QUIC. See src/moq/url.zig.
#
# The local relay is started and stopped here; anything else is expected to
# be reachable already. A relay that cannot be reached is recorded as such
# rather than skipped, so the matrix says why a row is empty.
set -uo pipefail

cd "$(dirname "$0")/.."

CLIENT=zig-out/bin/moq-test-client
RELAY=zig-out/bin/moq-relay
LOCAL_PORT=${LOCAL_PORT:-4455}
OUT=${OUT:-SPEC/moq-interop-results.md}
TMP=$(mktemp -d)
trap 'rm -rf "$TMP"; [ -n "${RELAY_PID:-}" ] && kill "$RELAY_PID" 2>/dev/null' EXIT

[ -x "$CLIENT" ] || { echo "build first: zig build" >&2; exit 1; }

if [ $# -gt 0 ]; then
  RELAYS=("$@")
  START_LOCAL=0
else
  RELAYS=(
    "moqt://127.0.0.1:$LOCAL_PORT/"
    "moqt://localhost:4448/anon"
    "https://localhost:4448/anon"
  )
  # Off by default: these need the network, and our TLS 1.3 does not
  # implement HelloRetryRequest, which Cloudflare's edge asks for.
  if [ "${PUBLIC:-0}" = 1 ]; then
    RELAYS+=("https://cdn.moq.dev/anon" "moqt://cdn.moq.dev:443/anon")
  fi
  START_LOCAL=1
fi

if [ "$START_LOCAL" = 1 ]; then
  "$RELAY" --port "$LOCAL_PORT" > "$TMP/relay.log" 2>&1 &
  RELAY_PID=$!
  sleep 1
fi

CASES=$("$CLIENT" --list)
DRAFTS=${DRAFTS:-"17 18"}

{
  echo "# MoQ interop results"
  echo
  echo "Generated by \`tools/moq_interop.sh\` on $(date -u '+%Y-%m-%d %H:%M UTC')."
  echo "Test cases and their pass criteria are the moq-interop-runner's:"
  echo "<https://github.com/englishm/moq-interop-runner/blob/main/docs/tests/TEST-CASES.md>"
  echo
  echo "\`moqt://\` rows are native QUIC, \`https://\` rows WebTransport."
  echo
  printf '| Relay | Draft |'
  for c in $CASES; do printf ' %s |' "$c"; done
  printf '\n|---|---|'
  for c in $CASES; do printf '%s' '---|'; done
  printf '\n'
} > "$TMP/out.md"

for url in "${RELAYS[@]}"; do
 for draft in $DRAFTS; do
  echo "=== $url draft-$draft ===" >&2
  "$CLIENT" --relay "$url" --draft "$draft" --tls-disable-verify > "$TMP/tap.txt" 2>"$TMP/err.txt"
  code=$?
  echo "  exit $code" >&2

  printf '| `%s` | %s |' "$url" "$draft" >> "$TMP/out.md"
  if grep -q '^Bail out!' "$TMP/tap.txt"; then
    reason=$(sed -n 's/^Bail out! //p' "$TMP/tap.txt" | head -1)
    for c in $CASES; do printf ' — |' >> "$TMP/out.md"; done
    printf '\n' >> "$TMP/out.md"
    echo "  unreachable: $reason" >&2
    continue
  fi
  for c in $CASES; do
    line=$(grep -E "^(ok|not ok) [0-9]+ - $c( |$)" "$TMP/tap.txt" | head -1)
    case "$line" in
      *"# SKIP"*) printf ' skip |' >> "$TMP/out.md" ;;
      "ok "*)     printf ' ✅ |'   >> "$TMP/out.md" ;;
      "not ok "*) printf ' ❌ |'   >> "$TMP/out.md" ;;
      *)          printf ' — |'    >> "$TMP/out.md" ;;
    esac
  done
  printf '\n' >> "$TMP/out.md"

  # Keep the failure reasons; a bare ❌ is not worth much on its own.
  # A passing test can carry a message too, so only report the ones that
  # belong to the failure above them.
  awk -v relay="$url draft-$draft" '
    /^ok /       { failing = 0 }
    /^not ok /   { failing = 1; name = substr($0, index($0, "- ") + 2) }
    /^  message:/{ if (failing) print "- `" relay "` " name ": " substr($0, 12) }
  ' "$TMP/tap.txt" >> "$TMP/notes.md" 2>/dev/null || true
 done
done

if [ -s "$TMP/notes.md" ]; then
  { echo; echo "## Failures"; echo; cat "$TMP/notes.md"; } >> "$TMP/out.md"
fi

mkdir -p "$(dirname "$OUT")"
# Only the table above KEEP_MARK is generated. Everything below it is written
# by hand — the runner-harness results and what they mean — so carry it over
# rather than overwriting the analysis with a fresh table.
KEEP_MARK='<!-- Everything below is written by hand; the generator keeps it. -->'
# awk compares the whole line literally, so the marker needs no escaping.
awk -v mark="$KEEP_MARK" '$0 == mark { keep = 1 } keep' "$OUT" 2>/dev/null > "$TMP/keep.md"
[ -s "$TMP/keep.md" ] || printf '%s\n' "$KEEP_MARK" > "$TMP/keep.md"
{ echo; cat "$TMP/keep.md"; } >> "$TMP/out.md"
cp "$TMP/out.md" "$OUT"
echo "wrote $OUT" >&2
cat "$OUT"
